    external_call(global.external_api_calendar_setvalue,0,Calendar_Year);
    external_call(global.external_api_calendar_setvalue,1,Calendar_Month);
    external_call(global.external_api_calendar_setvalue,2,Calendar_DayOfWeek);
    external_call(global.external_api_calendar_setvalue,3,Calendar_Day);
    external_call(global.external_api_calendar_setvalue,4,Calendar_Hour);
    external_call(global.external_api_calendar_setvalue,5,Calendar_Minute);
    external_call(global.external_api_calendar_setvalue,6,Calendar_Second);
    external_call(global.external_api_calendar_setvalue,7,Calendar_Milliseconds);
    external_call(global.external_api_calendar_writevalues,argument0);
